// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_tTcbZblvpwdL2oMWGTcD0zo9fIyzaOA',
    appId: '1:1091135017942:web:9251a9eeee79511f4b0a77',
    messagingSenderId: '1091135017942',
    projectId: 'ukrspetzevroprom-c9ec1',
    authDomain: 'ukrspetzevroprom-c9ec1.firebaseapp.com',
    storageBucket: 'ukrspetzevroprom-c9ec1.firebasestorage.app',
    measurementId: 'G-8B6NP9R36H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWpvZudLbj9NJ0FZWjU3SOMq5Ocmcmo2I',
    appId: '1:1091135017942:android:63174b115a6139094b0a77',
    messagingSenderId: '1091135017942',
    projectId: 'ukrspetzevroprom-c9ec1',
    storageBucket: 'ukrspetzevroprom-c9ec1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA54mARvIb9FW-8qvdTvxIcz8kabeFBBR4',
    appId: '1:1091135017942:ios:993d2e274baeab134b0a77',
    messagingSenderId: '1091135017942',
    projectId: 'ukrspetzevroprom-c9ec1',
    storageBucket: 'ukrspetzevroprom-c9ec1.firebasestorage.app',
    iosBundleId: 'com.example.ukrspetzevroprom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA54mARvIb9FW-8qvdTvxIcz8kabeFBBR4',
    appId: '1:1091135017942:ios:993d2e274baeab134b0a77',
    messagingSenderId: '1091135017942',
    projectId: 'ukrspetzevroprom-c9ec1',
    storageBucket: 'ukrspetzevroprom-c9ec1.firebasestorage.app',
    iosBundleId: 'com.example.ukrspetzevroprom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_tTcbZblvpwdL2oMWGTcD0zo9fIyzaOA',
    appId: '1:1091135017942:web:a3b67cb1fb073a364b0a77',
    messagingSenderId: '1091135017942',
    projectId: 'ukrspetzevroprom-c9ec1',
    authDomain: 'ukrspetzevroprom-c9ec1.firebaseapp.com',
    storageBucket: 'ukrspetzevroprom-c9ec1.firebasestorage.app',
    measurementId: 'G-KLF2460LYF',
  );
}
